### ISSUE TITLE
registry_key not handling large numbers properly

### ISSUE THREAD

**Issue by MikeLingenfelter** [inspec/inspec#2931]
### 🎛 Description
When testing for a DWORD Registry Value, if the value of the key is equal to or greater than 2^31 (2147483647) the returned value is a negative value.

**Test**:
describe registry_key('HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client') do
  its('Enabled') { should eq 0xffffffff }
end

**Test results:**
**Host value of 'Enabled' 0xffffffff (4294967295)**
  Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
     [MAJR]  Enabled should eq 4294967295

     expected: 4294967295
          got: -1

     (compared using ==)

**Host value of 'Enabled' 0x7FFFFFFF (2147483647)**
  Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
     [MAJR]  Enabled should eq 4294967295

     expected: 4294967295
          got: 2147483647

     (compared using ==)

**Host value of 'Enabled' 0x80000000 (2147483648)**
  Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
     [MAJR]  Enabled should eq 4294967295

     expected: 4294967295
          got: -2147483648

     (compared using ==)

🐛 bug report

regristry_key not returning the correct value of DWORD value.

### 🌍 InSpec and Platform Version

This has been tested and replicated on Windows 2012, 2012R2 and 2016.

Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
kitchen version: 1.20.0
inspec version: 1.51.21

### 🤔 Replication Case

We tested multiple values and the returned value breaks when you reach 2147483648 (0x80000000).

### 💁 Possible Solutions

N/A

### 💻 Stacktrace

N/A

**Comment by omar-irizarry** [comment]
This should have been fixed with pull request #2871 merged in v2.1.21

**Comment by MikeLingenfelter** [comment]
I updated to inspec 2.1.30.  I'm still seeing this issue with Windows 2012R2 and 2016.

**Comment by omar-irizarry** [comment]
are you using kitchen verify?
your issue report mentions inspec version 1.51.21.

**Comment by MikeLingenfelter** [comment]
i am.  is there another update i should apply?

**Comment by omar-irizarry** [comment]
Current version of ChefDk has inspec pinned to version 1.51.21.
if you installed inspec 2.1.30 you can run inspec as standalone instead of running kitchen verify.
so you would use a command similiar to this:
```
c:\opscode\inspec\bin\inspec exec c:\path\to\inspec\test.rb -t winrm://vagrant@127.0.0.1 -p 55985 --password vagrant
```
Looks like inspec version 2 will be included in a future release of ChefDk as it is already included in the Gemfile

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
