### ISSUE TITLE
Encoding issue with JSON reporter + .tar.gz profiles

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4135]
InSpec 4.3.2 from rubygems

This looks very similar to https://github.com/inspec/inspec/issues/3815 but
a. only affects tar'red profiles
b. Is due to non-ASCII chars in the profile itself and not in bad chars returned from the target host.

This is also very similar to https://github.com/inspec/inspec/issues/2938 but that issue affected all execution (not just when using JSON output) and also that issue was tested as fixed at the time.

This was originally raised as https://github.com/dev-sec/nginx-baseline/issues/33 but that was closed with a workaround.

**To reproduce:**
 * init a new profile
 * Edit `controls/example.rb` to be:

```
title 'My cool controls'

control 'control-01' do
  impact 1.0
  title 'Cool title'
  desc 'Check out my “cool” quote characters.'
  describe 'a' do
    it { should eq 'a' }
  end
end
```

Note the non-ASCII quote characters in the `desc`.

* Archive the profile
* Attempt to either exec the profile with the JSON reporter; or run the `json` command:

```
$> bundle exec inspec exec nginx_repro-0.1.0.tar.gz --reporter=json
bundler: failed to load command: inspec (/Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `encode'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `to_json'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters/json.rb:8:in `render'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/reporters.rb:39:in `render'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:129:in `block in render_output'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `each'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:128:in `render_output'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:153:in `run_tests'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/runner.rb:122:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/cli.rb:269:in `exec'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `load'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `<top (required)>'

$> bundle exec inspec json nginx_repro-0.1.0.tar.gz
bundler: failed to load command: inspec (/Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `encode'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/json-2.2.0/lib/json/common.rb:394:in `dump'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-4.3.2/lib/inspec/cli.rb:70:in `json'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/gems/inspec-bin-4.3.2/bin/inspec:15:in `<top (required)>'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `load'
  /Users/jamesstocks/code/bundles/compliance-profiles/ruby/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Workaround**
Declaring `# encoding: UTF-8` at the top of `controls/example.rb` avoids the error.

**Comment by miah** [comment]
Ah right, I remember seeing something similar when a letter with a diacritical mark was used.

**Comment by zenspider** [comment]
This profile runs fine for me on master so the quick fix is to update inspec.

I'd be happy to bisect this to track down the first version it was fixed in if you want... Lemme know.

**Comment by james-stocks** [comment]
This is still an issue in 4.16.0 from Rubygems

The list of instructions I follow is:

```
10547  bundle exec inspec init profile issue_4135
10548  vi issue_4135/controls/example.rb
10549  bundle exec inspec archive issue_4135
10550  bundle exec inspec json issue_4135-0.1.0.tar.gz
```

The `vi` command is me pasting the example control from the issue description into the profile.

The output is:

```
bundler: failed to load command: inspec (/Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/bin/inspec)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:224:in `encode'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:224:in `generate'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/json-2.2.0/lib/json/common.rb:394:in `dump'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/inspec-4.16.0/lib/inspec/cli.rb:88:in `json'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/inspec-4.16.0/lib/inspec/base_cli.rb:33:in `start'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/gems/inspec-bin-4.16.0/bin/inspec:11:in `<top (required)>'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/bin/inspec:23:in `load'
  /Users/jamesstocks/code/bundles/cool-project/ruby/2.6.0/bin/inspec:23:in `<top (required)>'
```

The issue description might have been a bit too verbose about what does/doesn't work - I cut it down a bit to just reproduction steps for the failing case.

**Comment by zenspider** [comment]
You are absolutely right. I now have a repro. Thank you for pushing back.

**Comment by zenspider** [comment]
I have a fix going through CI right now...
