### ISSUE TITLE
Misleading warning for aws resource packs

### ISSUE THREAD

**Issue by nbirnel** [inspec/inspec#4920]
# Describe the problem

```
inspec --version
4.18.85
```

Running `inspec exec . -t aws://`
Yields warnings for every single aws resource:
```
[2020-02-17T19:06:50-08:00] WARN: DEPRECATION: AWS resources shipped with core InSpec are being to moved to a resource pack for faster iteration. Please update your profiles
to depend on git@github.com:inspec/inspec-aws.git . Resource 'aws_security_group' (used at ./controls/neuralys.rb:9)
```
Tried with these three `inspec.yml` snippets:
```
depends:
  - name: inspec-aws
    url: git@github.com:inspec/inspec-aws.git
supports:
  platform: aws
```

```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
  platform: aws
```

```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.7.tar.gz
supports:
  platform: aws
```

Without the resource pack loading, I have been unable to use `aws_alb`, for instance.

## Possible Solution

I imagine I am simply doing something wrong. However, as a new user, this warning leads me nowhere useful. #4916 #4268 and #4092 seem to all refer to this, but I still do not see a reference which correctly tells me how to load the resource pack.

**Comment by finferflu** [comment]
@nbirnel this is what I have in my current setup and it works: 

```yml
supports:
  - platform: aws
depends:
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.7.zip
```

Have you removed the `inspec.lock` file every time you've made changes to the `inspec.yml` file?

**Comment by nbirnel** [comment]
@finferflu I had not tried that. Now that I have, I get:
```Traceback (most recent call last):
        27: from /usr/bin/inspec:203:in `<main>'
        26: from /usr/bin/inspec:203:in `load'
        25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.85/bin/inspec:11:in `<top (required)>'
        24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/base_cli.rb:35:in `start'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/cli.rb:289:in `exec'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:129:in `run'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `load'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `each'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:107:in `block in load'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `load_libraries'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each_with_index'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:265:in `block in load_libraries'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:272:in `load_libraries'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `load_libraries'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `each'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:144:in `block in load_libraries'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:159:in `load_library_file'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `load_with_context'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `instance_eval'
         3: from libraries/aws_alb.rb:3:in `load_with_context'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `require'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `eval'
libraries/aws_backend.rb:154:in `block in initialize': undefined method `resource' for :nope!:Symbol (NoMethodError)
Did you mean?  rescue
```
This continues to occur, even when I revert `inspec.yml` and remove `inspec.lock`.

**Comment by finferflu** [comment]
@nbirnel [I have seen that error](https://github.com/newcontext-oss/kitchen-terraform/issues/384), and it seems to be caused by Inspec version `4.18.85`. Regressing to version `4.18.51` has helped me. Try:

```sh
gem install inspec -v 4.18.51
```
And rerun `inspec`.

**Comment by michellehodges** [comment]
@finferflu any updates on this issue, whether its been fixed and we can use the latest version of inspec?

**Comment by stevendanna** [comment]
@michaellihs We believe the error `undefined method `resource' for :nope!:Symbol (NoMethodError)` has been fixed in the latest version of Inspec. If you are still seeing that problem, please let us know.

**Comment by nbirnel** [comment]
@stevendanna You are right; it is fixed. With 
```
inspec --version
4.18.100
```
and 
```
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.10.zip
```
when I run:
```
inspec exec neuralys -t aws://
```
I get:
```
Unexpected arguments found
```

**Comment by michellehodges** [comment]
@stevendanna @finferflu I'm still getting the following error: 

```
▶ inspec exec app/inspec -t aws://
Traceback (most recent call last):
	27: from /usr/local/bin/inspec:203:in `<main>'
	26: from /usr/local/bin/inspec:203:in `load'
	25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.85/bin/inspec:11:in `<top (required)>'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/base_cli.rb:35:in `start'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/cli.rb:289:in `exec'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:129:in `run'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `load'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `each'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:107:in `block in load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `load_libraries'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each_with_index'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:265:in `block in load_libraries'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:272:in `load_libraries'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `load_libraries'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `each'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:144:in `block in load_libraries'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:159:in `load_library_file'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `load_with_context'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `instance_eval'
	 3: from libraries/aws_alb.rb:3:in `load_with_context'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `require'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `eval'
libraries/aws_backend.rb:154:in `block in initialize': undefined method `resource' for :nope!:Symbol (NoMethodError)
Did you mean?  rescue
```

my `inspec.yml` file looks like this 

```
name: Inspec
title: Example Inspec
version: 0.1.0
inspec_version: '>= 4.6.9'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.10.zip
supports:
  - platform: aws

```
my `dynamo.rb` file looks like this

```
title "Test to ensure DynamoDB Table exists"

control "DynamoDB" do
  impact 1.0
  title "Ensure DynamoDB tables are properly configured"
  describe aws_dynamodb_table(table_name: 'Example') do
    it { should exist }
  end
end
```

For what it's worth, I do delete the `inspec.lock` file everytime before re-running.

**Comment by stevendanna** [comment]
@michellehodges From your error output, it appears you are seeing that on an older version.  The problem was fixed in a new releases. Please try v4.18.97 or greater.

**Comment by michellehodges** [comment]
@stevendanna Thanks -- that makes sense. I'm now encountering a new error...  For sanity sake, I also ran my working IAM Role inspec functionality which is currently working. I do delete my `inspec.lock` file before running.  

Issue: 
```
 ×  DynamoDB: Ensure DynamoDB tables are properly configured
     ×  AWS Dynamodb table  is expected to exist
     expected AWS Dynamodb table  to exist
  ✔  IAM Roles: Ensure IAM Roles are properly configured
     ✔  AWS IAM Role example-role is expected to exist
```

Here is the `dynamo.rb` file that I'm using: 

```
title "Test to ensure DynamoDB Table exists"

control "DynamoDB" do
  impact 1.0
  title "Ensure DynamoDB tables are properly configured"
  describe aws_dynamodb_table(table_name: 'Example') do
    it { should exist }
  end
end
```

Finally, my `inspec.yml` file: 

```
name: test
title: Test Inspec
version: 0.1.0
inspec_version: '>= 4.18.97'
depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/v1.6.10.zip
supports:
  - platform: aws
```
  
I'm running this under Admin, so my Principal should have the permissions it needs. I'm following instructions as listed [here](https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_dynamodb.md).

**Comment by michellehodges** [comment]
@stevendanna looks like my problem was a region issue in config. Sorry about that! Everything works well now.

**Comment by stevendanna** [comment]
@michellehodges Glad to hear things are working for you! Thanks for following up.
